using SlashText.Models;

namespace SlashText.Views;

// Screen-neutral content contract: later screens supply their own topics without copying the window.
public sealed record ScreenHelpTopic(string Id, string Group, string Title, string Icon, string Description,
    string[] Steps, string Tip, string? Target = null, string? Shortcut = null, string Demo = "tool");
public sealed record ScreenHelpDefinition(string Title, string Subtitle, ScreenHelpTopic[] Topics);

public static class CaptureHelpContent
{
    public static ScreenHelpDefinition Create(CaptureSettings settings) => new("Conheça a Captura",
        "Da primeira seleção à imagem pronta para compartilhar.",
    [
        new("start", "COMEÇAR", "Sua primeira captura", "Camera", "Escolha o tipo, ajuste a área e finalize. Tudo acontece localmente.",
            ["Selecione Imagem e escolha Região.", "Clique em Novo e arraste a área na tela.", "Anote se precisar; Capturar finaliza conforme sua regra."],
            "O guia usa exemplos ilustrados. Nenhum botão aqui inicia uma captura.", "CaptureNewButton", Demo: "region"),
        new("media", "COMEÇAR", "Imagem, vídeo e GIF", "Film", "A faixa ao lado de Novo escolhe o que será produzido.",
            ["Imagem permite capturar e anotar.", "Vídeo grava MP4; GIF cria uma animação de região.", "Confira destino, FPS, qualidade e cursor antes de gravar."],
            "A barra de edição de imagem fica oculta em vídeo/GIF. Edição temporal está prevista para outra etapa.", "CaptureImageMediaButton", Demo: "media"),
        new("delay", "COMEÇAR", "Atraso e abrir imagem", "Clock3", "Use o atraso para preparar a tela. Abrir imagem traz um arquivo estático para o editor.",
            ["Escolha Sem atraso ou um tempo disponível antes de Novo.", "Durante o atraso, prepare a janela desejada.", "Abrir imagem carrega um arquivo local; uma sessão alterada pede confirmação antes de ser substituída."],
            "GIF animado não é carregado como uma imagem estática editável.", "CaptureDelayBox", Demo: "time"),
        new("monitor", "TIPOS DE CAPTURA", "Monitor", "Monitor", "Captura a tela inteira do monitor ativo.",
            ["Selecione Monitor e clique em Novo, ou use seu atalho.", "A regra decide entre saída direta e revisão no editor."],
            "Confira a regra e o monitor ativo antes de capturar.", "CaptureMonitorModeButton", settings.ActiveMonitorShortcut, "region"),
        new("region", "TIPOS DE CAPTURA", "Região e alças", "ScanLine", "Escolha somente a área que interessa e ajuste antes de finalizar.",
            ["Arraste para criar a seleção.", "Use Selecionar: arraste um texto/emoji para movê-lo; arraste no vazio para mover a área. Ctrl+arraste move a área mesmo sobre uma anotação.", "As oito alças redimensionam a área. Setas movem o texto/emoji selecionado, ou a área quando nenhum objeto está selecionado; Shift aumenta o passo. R refaz a seleção e limpa suas marcações."],
            "As anotações permanecem sobre o conteúdo congelado da tela quando a área muda.", "CaptureRegionModeButton", settings.RegionShortcut, "region"),
        new("window", "TIPOS DE CAPTURA", "Janela", "AppWindow", "Captura a janela que estiver sob o cursor.",
            ["Escolha Janela ou use seu atalho.", "Posicione o cursor sobre a janela desejada.", "Confira o resultado no editor quando essa regra estiver ativa."],
            "Ocultar o SlashDesk durante a captura pode ser configurado em Regra de captura.", "CaptureWindowModeButton", settings.WindowShortcut, "region"),
        new("long", "TIPOS DE CAPTURA", "Captura longa", "ScrollText", "Junta o conteúdo de uma página com rolagem.",
            ["Escolha Captura longa ou use seu atalho.", "Durante o aviso inicial, posicione o cursor sobre a página.", "Aguarde a rolagem automática e confira a imagem inteira."],
            "O resultado depende de a página aceitar a rolagem. Conteúdo fixo ou dinâmico pode exigir conferência.", "CaptureScrollingModeButton", settings.ScrollingShortcut, "region"),
        new("bar", "BARRA DE CAPTURA", "Grupos da barra", "SlidersHorizontal", "As ferramentas são organizadas pela tarefa que você quer fazer.",
            ["Área ajusta a seleção; Anotar adiciona marcas e Privacidade oferece efeitos.", "Histórico desfaz/refaz. Finalizar reúne Capturar, Mais opções e Cancelar.", "A faixa inferior mostra propriedades da ferramenta ativa. Em pouco espaço, Mais opções mantém as ferramentas acessíveis."],
            "A barra usa o desktop congelado do início da seleção; o guia não demonstra uma captura real.", "CaptureRegionModeButton", Demo: "toolbar"),
        new("ink", "EDITOR E FERRAMENTAS", "Caneta, marca-texto e cores", "PenLine", "Desenhe livremente ou destaque um trecho.",
            ["Escolha Caneta ou Marca-texto e arraste na imagem.", "Ajuste espessura, cor e opacidade antes de desenhar.", "Na faixa de cores, use as setas e abra RGB para informar R/G/B ou hexadecimal."],
            "Ao desenhar, as propriedades afetam novas marcações. Para um objeto selecionado, confirme Aplicar alterações.", "CapturePencilToolButton", Demo: "ink"),
        new("shapes", "EDITOR E FERRAMENTAS", "Formas, setas e números", "Square", "Organize uma explicação com contornos, direção e passos numerados.",
            ["Na barra flutuante, Formas reúne retângulo, elipse, linha, seta e número.", "Arraste para desenhar formas; clique para inserir um número.", "Propriedades oferece contorno, preenchimento e reinício da numeração quando aplicável."],
            "No editor expandido, as ferramentas adicionais ficam visíveis; no compacto, use Mais ferramentas.", "CaptureRectangleToolButton", Demo: "shape"),
        new("text", "EDITOR E FERRAMENTAS", "Texto e fontes", "Type", "Adicione uma explicação legível sobre a imagem.",
            ["Escolha Texto e defina fonte, tamanho e cor.", "Clique na imagem e digite a anotação.", "No editor embutido, ajuste também negrito, itálico e alinhamento na faixa contextual."],
            "Para alterar um texto já inserido nesta sessão, use Selecionar e Aplicar alterações.", "CaptureTextToolButton", Demo: "text"),
        new("objects", "EDITOR E FERRAMENTAS", "Editar uma anotação", "MousePointer2", "Mova ou corrija uma anotação criada durante a sessão atual.",
            ["Escolha Selecionar e clique no texto, emoji, forma ou efeito; a borda indica a seleção. Texto e Emoji também permitem arrastar diretamente uma anotação do mesmo tipo.", "Arraste para mover, ou use as setas (Shift aumenta o passo). A moldura acompanha o arraste; a imagem é recomposta ao soltar. No editor, Ctrl+arraste navega mesmo sobre objetos.", "Ajuste cor/propriedades e clique em Aplicar alterações. Delete ou Excluir anotação remove somente esse objeto; Ctrl+Z desfaz. Na seleção da captura, textos e emojis também podem ser reposicionados antes de Capturar."],
            "Objetos são preservados na sessão, inclusive ao expandir o editor. PNG/JPEG reaberto contém pixels: as anotações antigas não voltam a ser objetos editáveis.", "CaptureSelectToolButton", "Delete · setas · Ctrl+Z", "objects"),
        new("emoji", "EDITOR E FERRAMENTAS", "Emojis e Meus emojis", "Smile", "Use o catálogo offline ou uma imagem pessoal como marcação.",
            ["Escolha Emojis e ajuste o tamanho antes de inserir.", "Ver todos oferece categorias, busca e páginas do catálogo.", "Meus emojis → Adicionar imagem importa PNG/JPEG. A cópia local preserva transparência; clique na imagem para inserir."],
            "Apagar o arquivo original não remove a cópia. Remover da coleção não altera marcações já existentes. Preserve a pasta inteira do piloto para manter sua coleção.", "CaptureStampToolButton", Demo: "emoji"),
        new("privacy", "EDITOR E FERRAMENTAS", "Desfocar e pixelizar", "ShieldCheck", "Aplique um efeito sobre uma região da imagem.",
            ["Escolha Desfocar ou Pixelizar e defina a intensidade.", "Arraste sobre o trecho desejado.", "Confira a saída copiada ou salva antes de compartilhar."],
            "O efeito é aplicado aos pixels da saída. Confira se a informação ficou suficientemente ocultada.", "CaptureMoreToolsButton", Demo: "privacy"),
        new("history", "EDITOR E FERRAMENTAS", "Desfazer, refazer e limpar", "Undo2", "Experimente ferramentas e corrija inserções sem começar tudo novamente.",
            ["Ctrl+Z desfaz; Ctrl+Y refaz.", "Na barra de captura, Mais opções → Limpar marcações remove as anotações.", "Refazer seleção (R) inicia uma nova área e limpa o histórico anterior."],
            "No editor, Descartar alterações retorna à última versão salva na sessão.", "CaptureWorkbenchUndoButton", "Ctrl+Z / Ctrl+Y", "toolbar"),
        new("zoom", "EDITOR E FERRAMENTAS", "Zoom e expandir editor", "Scaling", "Aproxime a imagem ou reserve mais espaço para trabalhar.",
            ["Use o seletor de zoom no rodapé do editor.", "Expandir editor amplia o espaço e mostra mais ferramentas.", "Voltar ao painel conserva a imagem e o histórico da sessão."],
            "Zoom só muda a visualização; não altera as dimensões exportadas.", "CaptureExpandEditorButton", Demo: "region"),
        new("crop", "EDITOR E FERRAMENTAS", "Recorte e redimensionamento", "Crop", "Ajuste a composição ou o tamanho final da imagem no editor.",
            ["Em Mais ferramentas, escolha Recorte e selecione a área.", "Confirme Aplicar recorte ou cancele a seleção.", "Redimensionar permite informar dimensões e conservar a proporção."],
            "Essas operações entram no histórico e podem ser desfeitas.", "CaptureMoreToolsButton", Demo: "region"),
        new("outputs", "SAÍDAS E REGRAS", "Copiar, salvar e concluir", "Copy", "Cada botão tem um resultado diferente.",
            ["Copiar envia a composição editada para a área de transferência, sem gravar arquivo.", "Salvar permite escolher o destino da cópia e registra o resultado nos Recentes.", "Concluir aplica a regra da captura. Em uma imagem aberta dos Recentes, atualiza o destino dessa entrada."],
            "As três saídas usam as edições da sessão, incluindo emojis e efeitos.", "CaptureSaveImageButton", Demo: "outputs"),
        new("rules", "SAÍDAS E REGRAS", "Regra de captura", "SlidersHorizontal", "Defina o que acontece depois de capturar.",
            ["Direta copia/salva conforme as opções; Editor permite revisar antes de concluir.", "Configure pasta, nome, PNG/JPEG, qualidade JPEG e retenção do histórico.", "Escolha se deve incluir cursor e ocultar o SlashDesk. Salvar regra aplica as alterações."],
            "Variáveis como {year}, {month}, {date}, {time}, {type} e {app} ajudam a organizar os arquivos.", "CaptureRuleButton", Demo: "outputs"),
        new("recents", "RECENTES E ATALHOS", "Carrossel de recentes", "Image", "Encontre e reutilize as capturas registradas localmente.",
            ["Busque por nome, tipo ou data e combine com o filtro. As setas navegam pelo carrossel.", "Uma imagem estática pode ser aberta no editor; os botões oferecem abrir, copiar, editar e excluir quando disponíveis.", "Ver todas abre o histórico completo em páginas de 25 entradas; nenhum arquivo ausente é apagado automaticamente."],
            "O carrossel mostra até 40 resultados; Ver todas dá acesso ao restante. Recentes guarda caminhos: preserve os arquivos nos seus destinos.", "CaptureHistoryScroller", Demo: "recents"),
        new("shortcuts", "RECENTES E ATALHOS", "Personalizar atalhos", "Keyboard", "Configure todas as combinações de captura no mesmo diálogo.",
            ["Abra Personalizar atalhos e clique no campo desejado.", "Pressione a combinação; cada ação deve ter um atalho diferente.", "Salve e teste. A roda exige Ctrl, Alt, Shift ou Win."],
            $"Seus atalhos atuais: Monitor {settings.ActiveMonitorShortcut}; Região {settings.RegionShortcut}; Janela {settings.WindowShortcut}; Longa {settings.ScrollingShortcut}.", "CaptureShortcutHelpTarget", Demo: "toolbar"),
        new("record", "GRAVAÇÕES", "Vídeo e GIF", "Video", "Grave localmente com as opções de qualidade e fluidez escolhidas.",
            ["Selecione Vídeo ou GIF e confira destino, FPS e qualidade.", "Inicie por Novo e use os controles disponíveis durante a gravação para pausar/retomar/finalizar.", "GIF oferece prévia antes de salvar; MP4 é gravado localmente em H.264."],
            "FPS altera a fluidez; qualidade altera a codificação. GIF e MP4 não usam as ferramentas de edição de imagem nesta etapa.", "CaptureVideoMediaButton", Demo: "media")
    ]);
}
